### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-role-git#1]
### Type of Report

Review Request

### Actual behaviour

Role had no initial review.

### Expected behaviour

Role must be reviewed and commented.

**Comment by Cinux90** [comment]
Because I Start to use some roles. I stuck because here is an issue in the role, so i will also perform now the Review :)
To my issue:
There is no variable like: wtd_git_packages but under defaults/main.yml: wtd_git_packagages.
